# Generated by Django 2.2.13 on 2020-07-31 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('ethnic', models.CharField(choices=[('SOMALI', 'SOMALI'), ('IRAN', 'IRAN'), ('SWAHILI', 'SWAHILI'), ('EGYPTIAN', 'EGYPTIAN'), ('INDONESIAN', 'INDONESIAN'), ('TURKISH', 'TURKISH'), ('ETHIOPIAN', 'ETHIOPIAN')], default='SOMALI', max_length=20)),
                ('dateofbirth', models.DateField()),
                ('family_size', models.CharField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
