# Generated by Django 2.2.13 on 2020-07-26 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_connections'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connections',
        ),
    ]
