# Generated by Django 2.2.13 on 2020-07-31 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_connections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dateofbirth',
        ),
    ]
