# Generated by Django 2.2.13 on 2020-08-01 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200731_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='date_field',
        ),
    ]
