# Generated by Django 2.2.13 on 2020-08-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200731_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_field',
            field=models.DateField(),
        ),
    ]
