# Generated by Django 2.2.13 on 2020-08-02 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200731_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_field',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
