# Generated by Django 3.0.7 on 2020-06-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanservices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='body',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='name',
        ),
        migrations.AddField(
            model_name='snippet',
            name='firstname',
            field=models.CharField(default='...', max_length=100),
        ),
        migrations.AddField(
            model_name='snippet',
            name='lastname',
            field=models.CharField(default='...', max_length=100),
        ),
    ]
