# Generated by Django 2.2.13 on 2020-06-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanservices', '0002_auto_20200616_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('ethnic', models.CharField(max_length=500)),
                ('family_size', models.CharField(max_length=500)),
                ('date_of_birth', models.CharField(max_length=500)),
            ],
        ),
    ]
