# Generated by Django 2.2.13 on 2020-07-23 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanservices', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
